/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Sugestao;
import controle.SugestaoControle;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class TelaListaDeSugestões extends javax.swing.JFrame {
    
    SugestaoControle controle = null;
    ArrayList<Sugestao> lista = null;
    
    

    /**
     * Creates new form TelaListaDeSugestões
     */
    public TelaListaDeSugestões() {
        try {
            initComponents();
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
            controle = new SugestaoControle("Sugestoes.txt"); 
            imprimirDadosSugestões(controle.recuperar());
            lista = new ArrayList<>(controle.recuperar());
            jTextFieldQtdeRegistros.setText("" + lista.size());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Ocorreu erro em algum componente de inicialização\n" + erro);
        }
    }
    
    public void imprimirDadosSugestões(ArrayList<Sugestao> lista)throws Exception{
        try {
            DefaultTableModel model = (DefaultTableModel) jTableListaDeSugestões.getModel();
            for (int pos = 0; pos < lista.size(); pos++) {
                String linha [] = new String [7];
                Sugestao aux = lista.get(pos);
                linha[0] = "" + aux.getId();
                linha[1] = new SimpleDateFormat("dd/MM/yyyy").format(aux.getDataDaSugestao());
                linha[2] = aux.getUsuario().getMatriculaCpf();
                linha[3] = aux.getUsuario().getNome().toUpperCase();
                linha[4] = aux.getUsuario().getTipoDeUsuario().toString();
                linha[5] = aux.getSugestao().toUpperCase();
                linha[6] = aux.getStatusDaSugestao().toString();
                model.addRow(linha);
                
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Ocorreu erro ao listar dados das sugestões nesta tabela.\n" + erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTableListaSugestões = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDeSugestões = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCadastroDeSugestões = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA CONTROLE DE BIBLIOTECA");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Relatório de sugestões");

        jTableListaDeSugestões.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA", "MAT. USUARIO", "NOME DO USUARIO", "TIPO USUARIO", "SUGESTÃO DE AQUISIÇÃO", "STATUS DA SUGESTÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaDeSugestões);
        if (jTableListaDeSugestões.getColumnModel().getColumnCount() > 0) {
            jTableListaDeSugestões.getColumnModel().getColumn(0).setMinWidth(45);
            jTableListaDeSugestões.getColumnModel().getColumn(0).setMaxWidth(45);
            jTableListaDeSugestões.getColumnModel().getColumn(1).setMinWidth(80);
            jTableListaDeSugestões.getColumnModel().getColumn(1).setMaxWidth(80);
            jTableListaDeSugestões.getColumnModel().getColumn(2).setMinWidth(100);
            jTableListaDeSugestões.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableListaDeSugestões.getColumnModel().getColumn(3).setMinWidth(180);
            jTableListaDeSugestões.getColumnModel().getColumn(3).setMaxWidth(180);
            jTableListaDeSugestões.getColumnModel().getColumn(4).setMinWidth(115);
            jTableListaDeSugestões.getColumnModel().getColumn(4).setMaxWidth(115);
            jTableListaDeSugestões.getColumnModel().getColumn(6).setMinWidth(110);
            jTableListaDeSugestões.getColumnModel().getColumn(6).setMaxWidth(110);
        }

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("IMPRIMIR");

        jButtonCadastroDeSugestões.setText("CADASTRO");
        jButtonCadastroDeSugestões.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroDeSugestõesActionPerformed(evt);
            }
        });

        jLabel2.setText("Quant. Registros:");

        javax.swing.GroupLayout jPanelTableListaSugestõesLayout = new javax.swing.GroupLayout(jPanelTableListaSugestões);
        jPanelTableListaSugestões.setLayout(jPanelTableListaSugestõesLayout);
        jPanelTableListaSugestõesLayout.setHorizontalGroup(
            jPanelTableListaSugestõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableListaSugestõesLayout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(jLabel1)
                .addContainerGap(421, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableListaSugestõesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastroDeSugestões)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );
        jPanelTableListaSugestõesLayout.setVerticalGroup(
            jPanelTableListaSugestõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableListaSugestõesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTableListaSugestõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonCadastroDeSugestões)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTableListaSugestões, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTableListaSugestões, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 392, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonCadastroDeSugestõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroDeSugestõesActionPerformed
        try {
            TelaCadSugestao tela = new TelaCadSugestao();
            tela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaListaDeSugestões.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroDeSugestõesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaDeSugestões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaDeSugestões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaDeSugestões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaDeSugestões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaDeSugestões().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroDeSugestões;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTableListaSugestões;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaDeSugestões;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
