/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.AreaDoLivro;
import controle.AreaControle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class TelaCadArea extends javax.swing.JFrame {

    AreaControle areaControle = null;
    
    /**
     * Creates new form TelaCadArea
     */
    public TelaCadArea() throws Exception {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        areaControle = new AreaControle("Areas.txt");
        imprimirDadosAreaGrid(areaControle.recuperar());
       jButtonImportarCDD.setEnabled(false);

    }

    private void imprimirDadosAreaGrid(ArrayList<AreaDoLivro> lista) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableAreaConhecimento.getModel();
        model.setNumRows(0);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[3];
            AreaDoLivro aux = lista.get(pos);
            linha[0] = "" + aux.getId();
            linha[1] = aux.getCdd();
            linha[2] = aux.getDescricaoDaArea().toUpperCase();
            model.addRow(linha);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadArea = new javax.swing.JPanel();
        jButtonImportarCDD = new javax.swing.JButton();
        jButtonListagemArea = new javax.swing.JButton();
        jButtonFecharCadastroArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAreaConhecimento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA CONTROLE DE BIBLIOTECA");
        setResizable(false);

        jButtonImportarCDD.setText("IMPORTAR");
        jButtonImportarCDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarCDDActionPerformed(evt);
            }
        });

        jButtonListagemArea.setText("LISTAGEM");
        jButtonListagemArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemAreaActionPerformed(evt);
            }
        });

        jButtonFecharCadastroArea.setText("FECHAR");
        jButtonFecharCadastroArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCadastroAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadAreaLayout = new javax.swing.GroupLayout(jPanelCadArea);
        jPanelCadArea.setLayout(jPanelCadAreaLayout);
        jPanelCadAreaLayout.setHorizontalGroup(
            jPanelCadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonImportarCDD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListagemArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFecharCadastroArea))
        );
        jPanelCadAreaLayout.setVerticalGroup(
            jPanelCadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadAreaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelCadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListagemArea)
                    .addComponent(jButtonFecharCadastroArea)
                    .addComponent(jButtonImportarCDD))
                .addGap(16, 16, 16))
        );

        jTableAreaConhecimento.setAutoCreateRowSorter(true);
        jTableAreaConhecimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "COD. CDD", "DESCRICAO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAreaConhecimento.setEnabled(false);
        jTableAreaConhecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAreaConhecimentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAreaConhecimento);
        if (jTableAreaConhecimento.getColumnModel().getColumnCount() > 0) {
            jTableAreaConhecimento.getColumnModel().getColumn(0).setMinWidth(40);
            jTableAreaConhecimento.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableAreaConhecimento.getColumnModel().getColumn(1).setMinWidth(80);
            jTableAreaConhecimento.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jLabel1.setText("CADASTRO DE ÁREA DE CONHECIMENTO DO LIVRO");

        jLabel2.setText("IMPORTAÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCadArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImportarCDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarCDDActionPerformed
        try {
            areaControle.importarTabelaCdd("CDD.txt");
            imprimirDadosAreaGrid(areaControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonImportarCDDActionPerformed

    private void jButtonListagemAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemAreaActionPerformed
        try {
            TelaListaDeAreas areas = new TelaListaDeAreas();
            areas.setVisible(true);
            dispose();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonListagemAreaActionPerformed

    private void jTableAreaConhecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAreaConhecimentoMouseClicked
        try {

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jTableAreaConhecimentoMouseClicked

    private void jButtonFecharCadastroAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadastroAreaActionPerformed
        try {
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonFecharCadastroAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadArea().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaCadArea.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharCadastroArea;
    private javax.swing.JButton jButtonImportarCDD;
    private javax.swing.JButton jButtonListagemArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelCadArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAreaConhecimento;
    // End of variables declaration//GEN-END:variables
}
