/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Livro;
import controle.LivroControle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class TelaListaLivros extends javax.swing.JFrame {

    LivroControle controle;
    ArrayList<Livro> lista = null;

    /**
     * Creates new form TelaListaLivros
     */
    public TelaListaLivros() throws Exception {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        try {
            controle = new LivroControle("livro.txt");
            lista = new ArrayList<>(controle.recuperar());
            jTextFieldQtdeRegistros.setText(""+lista.size());

            imprimirDadosDoLivroEmLista(controle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao listar os livros\n" + erro.getStackTrace());
        }
    }

    private void imprimirDadosDoLivroEmLista(ArrayList<Livro> listaDeLivros) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableListaLivros.getModel();
        model.setNumRows(0);
        for (int pos = 0; pos < listaDeLivros.size(); pos++) {
            String[] linha = new String[9];
            Livro aux = listaDeLivros.get(pos);
            linha[0] = " " + aux.getId();
            linha[1] = aux.getIsbn();
            linha[2] = aux.getTituloLivro().toUpperCase();
            linha[3] = aux.getSubTituloLivro().toUpperCase();
            linha[4] = aux.getAutor().getNomeAutor().toUpperCase();
            linha[5] = aux.getEditora().getDescricaoEditora().toUpperCase();
            linha[6] = aux.getArea().getCdd() + "-" + aux.getArea().getDescricaoDaArea().toUpperCase();
            linha[7] = aux.getEdicao();
            linha[8] = "" + aux.getAnoDePublicacao();
            model.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaLivros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaLivros = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Controle de Biblioteca");
        setResizable(false);

        jLabel1.setText("Relatório de Livros Cadastrados no Sistema");

        jTableListaLivros.setAutoCreateRowSorter(true);
        jTableListaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "TÍTULO", "SUB-TÍTULO", "AUTOR", "EDITORA", "ÁREA", "EDIÇÃO", "ANO PUBLIC."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaLivrosMouseClicked(evt);
            }
        });
        jTableListaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableListaLivrosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaLivros);
        if (jTableListaLivros.getColumnModel().getColumnCount() > 0) {
            jTableListaLivros.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaLivros.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaLivros.getColumnModel().getColumn(1).setMinWidth(120);
            jTableListaLivros.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableListaLivros.getColumnModel().getColumn(7).setMinWidth(60);
            jTableListaLivros.getColumnModel().getColumn(7).setMaxWidth(60);
            jTableListaLivros.getColumnModel().getColumn(8).setMinWidth(60);
            jTableListaLivros.getColumnModel().getColumn(8).setMaxWidth(60);
        }

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButton1.setText("IMPRIMIR");

        jButtonCadastro.setText("CADASTRO");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("Quant. de Registros:");

        jTextFieldQtdeRegistros.setEditable(false);

        javax.swing.GroupLayout jPanelListaLivrosLayout = new javax.swing.GroupLayout(jPanelListaLivros);
        jPanelListaLivros.setLayout(jPanelListaLivrosLayout);
        jPanelListaLivrosLayout.setHorizontalGroup(
            jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaLivrosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                        .addComponent(jButtonCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaLivrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(360, 360, 360))
        );
        jPanelListaLivrosLayout.setVerticalGroup(
            jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLivrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButton1)
                    .addComponent(jButtonCadastro)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        try {

            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaListaLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTableListaLivrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaLivrosKeyReleased

    }//GEN-LAST:event_jTableListaLivrosKeyReleased

    private void jTableListaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaLivrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableListaLivrosMouseClicked

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed

        try {
            TelaCadastroLivros tela = new TelaCadastroLivros();
            tela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaListaLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaListaLivros().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaListaLivros.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListaLivros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaLivros;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
